# Generated by Django 3.2.2 on 2021-05-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_active',
            field=models.BooleanField(default=False),
        ),
    ]
