# Generated by Django 3.2.2 on 2021-08-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20210810_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_start_date',
            field=models.DateField(),
        ),
    ]
