# Generated by Django 3.2.2 on 2021-08-17 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0006_auto_20210810_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('gen_report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gen_report_title', models.TextField(max_length=100)),
                ('gen_report_active', models.BooleanField(default=False)),
                ('gen_report_start_date', models.DateField()),
                ('gen_report_end_date', models.DateField()),
                ('gen_report_subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.subject')),
                ('gen_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
