# Generated by Django 3.2.2 on 2021-08-17 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_studentreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentReport',
        ),
    ]
