# Generated by Django 3.2.2 on 2021-08-17 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0008_delete_studentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('gen_report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gen_report_start_date', models.DateField()),
                ('gen_report_end_date', models.DateField()),
                ('gen_report_file', models.FileField(upload_to='reports/')),
                ('gen_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
