# Generated by Django 3.2.2 on 2021-08-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_generatedreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='gen_report_file',
            field=models.TextField(max_length=200),
        ),
    ]
