# Generated by Django 3.2.2 on 2021-09-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_alter_generatedreport_gen_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='gen_report_additional_comment',
            field=models.TextField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
