# Generated by Django 3.2.2 on 2021-09-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_generatedreport_gen_report_additional_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedreport',
            name='gen_report_additional_comment',
        ),
        migrations.AddField(
            model_name='report',
            name='report_additional_comment',
            field=models.TextField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
