# Generated by Django 3.2.2 on 2021-09-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20210916_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_additional_comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
