# Generated by Django 3.2.2 on 2021-05-24 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badge_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('badge_title', models.TextField(max_length=100)),
                ('badge_description', models.TextField(max_length=500)),
                ('badge_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('allocation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alloc_date', models.DateTimeField(auto_now=True)),
                ('badge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge.badge')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_badge', to=settings.AUTH_USER_MODEL)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_badge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
