# Generated by Django 3.2.2 on 2021-08-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='badge_image',
            new_name='badge_allocated_image',
        ),
    ]
