# Generated by Django 3.2.2 on 2021-08-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_rename_badge_image_badge_badge_allocated_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_allocated_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/badges'),
        ),
    ]
