# Generated by Django 3.2.2 on 2021-08-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0003_alter_badge_badge_allocated_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_how_to_obtain',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_unallocated_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/badges'),
        ),
    ]
