# Generated by Django 3.2.2 on 2021-09-16 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0005_badge_badge_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='badge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alloc_list', to='badge.badge'),
        ),
    ]
