# Generated by Django 3.2.2 on 2021-10-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0006_alter_allocation_badge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_title',
            field=models.TextField(max_length=200),
        ),
    ]
