# Generated by Django 3.2.2 on 2021-09-17 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('comment_image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_image_desc', models.TextField(blank=True, max_length=200, null=True)),
                ('comment_image_file', models.ImageField(upload_to='images/')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment')),
            ],
        ),
    ]
