# Generated by Django 3.2.2 on 2021-05-24 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_title', models.TextField(max_length=100)),
                ('entry_content', models.TextField(max_length=500)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
            ],
        ),
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('entry_image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_image_desc', models.TextField(blank=True, max_length=200, null=True)),
                ('entry_image_file', models.ImageField(upload_to='images/')),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.entry')),
            ],
        ),
    ]
